/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello_api_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hosts */
        get: operations["hosts_api_hosts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Db Ok */
            db_ok: boolean;
            /** Version */
            version: string;
        };
        /** HelloResponse */
        HelloResponse: {
            /** Message */
            message: string;
            /** Version */
            version: string;
            /** Db Ok */
            db_ok: boolean;
        };
        /** HostRow */
        HostRow: {
            /** Status */
            status: string;
            /** Host */
            host: string;
            /** Uptime */
            uptime: string;
            /** Override */
            override: string;
            /** Role */
            role: string;
            /** Os */
            os: string;
            /** Sha */
            sha: string;
            /** Vlt Sha */
            vlt_sha: string;
            /** Mtime */
            mtime: string;
            /** Err */
            err: string;
            /** Tc Quar */
            tc_quar: string;
            /** Tc Act */
            tc_act: string;
            /** Tc J Sf */
            tc_j_sf: string;
            /** Pp Last */
            pp_last: string;
            /** Pp Sha */
            pp_sha: string;
            /** Pp Exp */
            pp_exp: string;
            /** Pp Match */
            pp_match: string;
            /** Healthy */
            healthy: string;
            /** Data */
            data: string;
            /** Note */
            note: string;
        };
        /** HostsResponse */
        HostsResponse: {
            /** Rows */
            rows: components["schemas"]["HostRow"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            summary: components["schemas"]["HostsSummary"];
        };
        /** HostsSummary */
        HostsSummary: {
            /** Version */
            version: string;
            /** Db Path */
            db_path: string;
            /** Total Hosts */
            total_hosts: number;
            /** Fqdn Suffix */
            fqdn_suffix: string | null;
            /** Log Size Warnings */
            log_size_warnings: string[];
            /** Data Is Stale */
            data_is_stale: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    hello_api_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponse"];
                };
            };
        };
    };
    hosts_api_hosts_get: {
        parameters: {
            query?: {
                /** @description Filter expression using the host-monitor DSL (e.g. os=linux pp_last>1h) */
                filter?: string;
                /** @description Sort spec (e.g. pp_last:desc or host:asc). Also accepted inline in filter via sort: prefix. */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
