#!/usr/bin/env bash

set -e
# set -x

# takes in branch name and creates an override file for that branch

if [ -z "$1" ]; then
  echo "you must specify a branch name"
  exit 1
fi

branch_name="$1"
script_dir=$(dirname "$0")
# resolve user_override_dir to absolute path
user_override_dir="$(realpath "$script_dir/../configs/local/overrides")"
override_file="$user_override_dir/${branch_name}.override"
# get $user from username
user=$(whoami)

# check if it already exists
if [ -f "$override_file" ]; then
  echo "override file $override_file already exists"
  exit 1
fi

cat <<EOF > "$override_file"
# If you place this file at \`/etc/puppet/ronin_settings\`
# the \`run-puppet.sh\` script will use the values here.

# Override file autogenerated by create_override.sh for:
#   branch: $branch_name
#   user: $user

# puppet overrides
PUPPET_REPO="https://github.com/$user/ronin_puppet.git"
PUPPET_BRANCH="$branch_name"
PUPPET_MAIL="$user@mozilla.com"

# taskcluster overrides
# WORKER_TYPE_OVERRIDE='gecko-t-linux-talos-1804-staging'
EOF

echo "Created override file: $override_file"
echo "  PUPPET_BRANCH: $branch_name"
echo "  PUPPET_REPO: https://github.com/$user/ronin_puppet.git"
echo "  PUPPET_MAIL: $user@mozilla.com"
