#!/usr/bin/env bash

set -e
# set -x

# Creates a puppet override file for a branch.
#
# Accepts one of:
#   - a GitHub PR URL   (e.g. https://github.com/mozilla-platform-ops/ronin_puppet/pull/123)
#   - a bare PR number  (e.g. 123 -- assumes the mozilla-platform-ops/ronin_puppet repo)
#   - a branch name     (e.g. my-branch or aerickson/some-branch)
#
# In PR mode the branch, repo (handles forks), and a descriptive filename are
# derived from the PR via the `gh` CLI, and the PR url/title are recorded as
# comments in the override file.

UPSTREAM_REPO="mozilla-platform-ops/ronin_puppet"
UPSTREAM_REPO_URL="https://github.com/${UPSTREAM_REPO}.git"

if [ -z "$1" ]; then
  echo "usage: $0 <pr-url | pr-number | branch-name>"
  exit 1
fi

input="$1"
script_dir=$(dirname "$0")
# resolve user_override_dir to absolute path
user_override_dir="$(realpath "$script_dir/../configs/overrides")"
# get $user from username
user=$(whoami)

# Defaults (branch mode); overridden below in PR mode.
puppet_repo="$UPSTREAM_REPO_URL"
pr_url=""
pr_title=""

if [[ "$input" =~ ^https?:// || "$input" =~ ^[0-9]+$ ]]; then
  # ---- PR mode -------------------------------------------------------------
  if ! command -v gh >/dev/null 2>&1; then
    echo "PR mode requires the 'gh' CLI (https://cli.github.com/)"
    exit 1
  fi

  repo_flag=()
  if [[ "$input" =~ ^[0-9]+$ ]]; then
    # Bare number: assume the upstream repo.
    repo_flag=(--repo "$UPSTREAM_REPO")
  fi

  # Fetch the fields we need as a single tab-separated line.
  pr_tsv=$(gh pr view "$input" "${repo_flag[@]}" \
    --json number,title,headRefName,isCrossRepository,headRepositoryOwner,headRepository,url \
    --jq '[.number, .title, .headRefName, (.isCrossRepository|tostring), .headRepositoryOwner.login, .headRepository.name, .url] | @tsv') || {
    echo "failed to fetch PR: $input"
    exit 1
  }

  IFS=$'\t' read -r pr_number pr_title branch_name is_cross head_owner head_repo pr_url <<<"$pr_tsv"

  # For a cross-repository (fork) PR, point PUPPET_REPO at the fork.
  if [ "$is_cross" = "true" ]; then
    puppet_repo="https://github.com/${head_owner}/${head_repo}.git"
  fi

  # Build a readable, stable filename: pr-<num>-<title-slug>.
  # Lowercase, turn runs of non-alphanumerics into single dashes, trim, cap length.
  slug=$(printf '%s' "$pr_title" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')
  slug="${slug#-}"
  slug="${slug%-}"
  slug=$(printf '%s' "$slug" | cut -c1-50)
  slug="${slug%-}"
  safe_name="pr-${pr_number}-${slug}"
else
  # ---- branch-name mode ----------------------------------------------------
  branch_name="$input"
  # Branch names can contain slashes (e.g. "aerickson/san-juan"). The slash is
  # only a problem for the filename, so sanitize it for the file path while
  # keeping the real branch name in PUPPET_BRANCH below.
  safe_name="${branch_name//\//_}"
fi

override_file="$user_override_dir/${safe_name}.override"

# check if it already exists
if [ -f "$override_file" ]; then
  echo "override file $override_file already exists"
  exit 1
fi

# Build the "autogenerated for" comment block.
info_lines="#   branch: $branch_name
#   user: $user"
if [ -n "$pr_url" ]; then
  info_lines="$info_lines
#   pr: $pr_url
#   title: $pr_title"
fi

# Build the PUPPET_REPO block. In branch mode, keep a commented hint pointing at
# the user's fork; in PR mode the active repo is already correct.
repo_block="PUPPET_REPO=\"$puppet_repo\""
if [ -z "$pr_url" ]; then
  repo_block="$repo_block
# PUPPET_REPO=\"https://github.com/$user/ronin_puppet.git\""
fi

cat <<EOF > "$override_file"
# If you place this file at \`/etc/puppet/ronin_settings\`
# the \`run-puppet.sh\` script will use the values here.

# Override file autogenerated by create_override.sh for:
$info_lines

# puppet overrides
$repo_block
PUPPET_BRANCH="$branch_name"
PUPPET_MAIL="$user@mozilla.com"

# taskcluster overrides
# WORKER_TYPE_OVERRIDE='gecko-t-linux-talos-1804-staging'
EOF

echo "Created override file: $override_file"
echo "  PUPPET_BRANCH: $branch_name"
echo "  PUPPET_REPO: $puppet_repo"
echo "  PUPPET_MAIL: $user@mozilla.com"
if [ -n "$pr_url" ]; then
  echo "  PR: $pr_url"
fi
